ALTER TABLE user
MODIFY name VARCHAR(255) NOT NULL,
MODIFY login VARCHAR(255) NOT NULL,
MODIFY user_password VARCHAR(255) NOT NULL,
MODIFY CPF VARCHAR(255) NOT NULL,
MODIFY birth_date VARCHAR(255) NOT NULL,
MODIFY phone_number VARCHAR(255) NOT NULL,
MODIFY CEP VARCHAR(255) NOT NULL;